### PR TITLE
Added Support for Orca Slicer

### PR DESCRIPTION
**Pull request by lastowl**
Created Pull request against Development Branch.

Looking at adding Metadata support from end of Gcode.

### CODE REVIEW

**Comment by lastowl** [comment]
There is metadata at the end of the file which could be used instead, I'll look at switching to using that.

Here's an example file with the metadata (at the end)
`http://sanity.fail/Cube_PETG_1d11h36m.gcode`

**Comment by NilsRo** [comment]
> There is metadata at the end of the file which could be used instead, I'll look at switching to using that.
> 
> Here's an example file with the metadata (at the end) http://sanity.fail/Cube_PETG_1d11h36m.gcode

For the remaining time you should stay with M73 as they are updated during printing. Has the user enable M73 commands or are they active by default?

The metadata should be taken care off in the metadata processing that it can be used there also. If you like you can add it or I can do it...

**Comment by lastowl** [comment]
Your right, just checked the metadata is identical to PrusaSlicer which makes sense since it's a fork of BambuSlicer which is a fork of PrusaSlicer. 
With M73 commands isn't that printer specific rather than slicer?

**Comment by NilsRo** [comment]
M73 is standard but not supported by any printer or any slicer. I try to use the slicer standard to avoid changing settings for slicer estimator plugin. But if it is a PrusaSlicer fork M73 is the only way to get the remaining time I am sure. 

So you can use the implementation for Prusa and SuperSlicer which is also a fork.

**Comment by NilsRo** [comment]
If you like I would add the missing code. Is not that much....

**Comment by lastowl** [comment]
Sorry, should be sorted now

**Pull request merged**
